version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-url-shortener
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: url_shortener
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
